### ISSUE TITLE
Support Node.js > 0.10.x

### ISSUE THREAD

**Issue by zdne** [apiaryio/fury.js#25]
This includes both Node.js v0.12 and higher and io.js

**Comment by freaz** [comment]
It seems to be that Robotskirt package doesn't support node v0.12.

**Comment by danielgtaylor** [comment]
@freaz we are looking at options to move away from this package. Our goal is to support all modern versions of Node (and iojs).

**Comment by zdne** [comment]
@freaz @danielgtaylor as discussed we will remove Markdown rendering (hence robot skirt) from Fury.js

**Comment by Almad** [comment]
@danielgtaylor @freaz @zdne I've discussed with various people, and I'd replace robotskirt with commonmark if possible as it holds the whole platform on 0.10.

Do you think it would be feasible to do a pre-relase of fury with tose two replaced for testing?

**Comment by Baggz** [comment]
@Almad @zdne @danielgtaylor 

We have agreed that the Core Application team will replace Robotskirt as the Markdown rendering is part of the [Metamorphoses](https://github.com/apiaryio/metamorphoses) package.

Please correct me if I'm wrong.

**Comment by Almad** [comment]
@Baggz OK, thought we are going to decouple those two...so let's see.

**Comment by zdne** [comment]
@Baggz @Almad 

CAT to remove robotskirt from Fury.js AFTER the MSON production-ready release.

**Comment by zdne** [comment]
cc @kylef

**Comment by Almad** [comment]
OK

**Comment by danielgtaylor** [comment]
Fury 1.x now supports all versions of Node.js.
