### ISSUE TITLE
Use exportSourcemap instead of generateSourceMap

### ISSUE THREAD

**Issue by smizell** [apiaryio/fury.js#58]
See here https://github.com/apiaryio/fury-adapter-swagger/issues/26

This change will be needed in both Fury and all adapters.

**Comment by smizell** [comment]
cc @pksunkara

**Comment by pksunkara** [comment]
Closing since the discussion is resolved. https://github.com/apiaryio/fury-adapter-swagger/issues/26#issuecomment-164501633
