### ISSUE TITLE
Fury should expose detected format

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/fury.js#62]
Fury iterates over adapters and uses their `adapter.detect()` function to detect input format. Result of the detection should be exposed in Fury's result for further use by subsequent tooling.

As of now, the detection behavior fully overlaps with behavior of [Deckard Cain](https://github.com/apiaryio/deckardcain), but that's rather an coincidence and implementation detail, so in the future, subsequent tooling shouldn't rely on that.

**Comment by kylef** [comment]
@honzajavorek What output would you expect to see from a detect format. One of the possible content types, or perhaps the full name?

**Comment by honzajavorek** [comment]
I'd prefer the media type over a human-readable name.

**Comment by honzajavorek** [comment]
I believe this is already released?

**Comment by kylef** [comment]
Yes it was, made it into Fury 3.0.0-beta.3
